# Generated by Django 6.0.1 on 2026-01-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc', '0003_refreshtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSAKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid', models.CharField(max_length=50, unique=True)),
                ('private_key', models.TextField(help_text='PEM format')),
                ('public_key', models.TextField(help_text='PEM format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
